name: flutter_template
description: "A Flutter template project with Clean Architecture, BLoC, and mocked datasources."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # Environment
  flutter_dotenv: ^5.2.1

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Functional Programming
  dartz: ^0.10.1

  # HTTP
  http: ^1.4.0

  # Internationalisation (date & currency formatting)
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
