name: flutter_template
description: "A Flutter template project with Clean Architecture, BLoC, and mocked datasources."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Environment
  flutter_dotenv: ^5.2.1

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_crashlytics: ^4.3.1

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

  # Functional Programming
  dartz: ^0.10.1

  # HTTP
  http: ^1.4.0

  # Image Cache
  cached_network_image: ^3.4.1

  # Internationalisation (date & currency formatting)
  intl: ^0.20.2
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  get_it: ^9.2.1
  provider: ^6.1.2
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lang/
